### ISSUE TITLE
Publish to crates-io?

### ISSUE THREAD

**Issue by cryscan** [KerfuffleV2/repugnant-pickle#2]
This crate is awesome! Would you like to publish it so that crates depend on this one could be published?

**Comment by KerfuffleV2** [comment]
@cryscan 

I am really really sorry it took so long to respond! Also thank you for the kind words. I had to hopes to clean up the project before publishing but I just never actually had the time so I guess I will just publish it in the current state. 

https://crates.io/crates/repugnant-pickle

Please let me know if you run into issues using that and hopefully it won't take so long to get a reply.
